# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # Prevent Dependabot from updating LSP4J to new versions
      # TODO[#232]: Remove this block after updating to the new PSES
      - dependency-name: "org.eclipse.lsp4j:org.eclipse.lsp4j"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
